micronaut:
  application:
    name: maintainer
  server:
    port: 8081
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          jwks:
            keycloak:
              url: '${OAUTH_JWKS:`http://localhost:8080/realms/jics/protocol/openid-connect/certs`}'
  http:
    services:
      keycloak:
        url: '${OAUTH_TOKEN_URL:`http://localhost:8080/realms/jics/protocol/openid-connect`}'
services:
  keycloak:
    grant-type: 'urn:ietf:params:oauth:grant-type:uma-ticket'
    audience: 'backend'

r2dbc:
  datasources:
    default:
      schema-generate: CREATE_DROP
      dialect: ${R2DBC_DIALECT:POSTGRES}
      url: ${R2DBC_URL:r2dbc:postgresql://localhost:5432/postgres}
      username: keycloak
      password: password
netty:
  default:
    allocator:
      max-order: 3
